# Generated by Django 5.2.3 on 2025-07-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brazilianaddress',
            name='complement',
            field=models.CharField(blank='True', max_length=255, null=True, verbose_name='Address Complement'),
        ),
        migrations.AddField(
            model_name='brazilianaddress',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='brazilianaddress',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Neighborhood'),
        ),
    ]
