# Generated by Django 5.2.3 on 2025-07-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_brasilianstate_alter_brazilianaddress_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brasilianstate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brasilianstate',
            name='sigla',
            field=models.CharField(max_length=2, verbose_name='Sigla'),
        ),
    ]
