# Generated by Django 5.2.3 on 2025-07-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_brasilianstate_name_alter_brasilianstate_sigla'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrasilianState',
            new_name='BrazilianState',
        ),
    ]
