# Generated by Django 5.2.3 on 2025-07-03 01:36

from django.db import models, migrations

DEFAULT_BRAZILIAN_STATES = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins')
)
def add_brazilian_states(apps, schema_editor):
    State = apps.get_model('address', 'BrazilianState')

    for sigla, name in DEFAULT_BRAZILIAN_STATES:
        state = State(sigla=sigla, name=name)
        state.save()

def remove_brazilian_states(apps, schema_editor):
    # This is used to migrate backward
    # You can remove your dog types, or just pass
    # pass
    State = apps.get_model('address', 'BrazilianState')
    for sigla, name in DEFAULT_BRAZILIAN_STATES:
        state = State.objects.get(sigla=sigla)
        state.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_brasilianstate_name_alter_brasilianstate_sigla'),
    ]

    operations = [
        migrations.RunPython(add_brazilian_states, remove_brazilian_states),
    ]
