# Generated by Django 5.2.3 on 2025-07-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_rename_brasilianstate_brazilianstate'),
        ('address', '0006_auto_20250703_0136'),
    ]

    operations = [
    ]
