# Generated by Django 5.2.3 on 2025-07-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_merge_20250703_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brazilianaddress',
            old_name='street',
            new_name='logradouro',
        ),
    ]
