# Generated by Django 5.2.3 on 2025-07-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_rename_street_brazilianaddress_logradouro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brazilianaddress',
            name='logradouro',
            field=models.CharField(max_length=255, verbose_name='Logradouro'),
        ),
    ]
