# Generated by Django 5.2.3 on 2025-07-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_alter_brazilianaddress_logradouro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brazilianaddress',
            old_name='state',
            new_name='estado',
        ),
    ]
