# Generated by Django 5.2.3 on 2025-07-23 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_rename_state_brazilianaddress_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brazilianaddress',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.brazilianstate', verbose_name='Estado ou Distrito'),
        ),
    ]
