# Generated by Django 5.2.3 on 2025-07-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_alter_brazilianaddress_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brazilianaddress',
            old_name='city',
            new_name='cidade',
        ),
    ]
