# Generated by Django 5.2.3 on 2025-07-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_rename_city_brazilianaddress_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brazilianaddress',
            old_name='number',
            new_name='numero',
        ),
        migrations.AlterField(
            model_name='brazilianaddress',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
    ]
