# Generated by Django 5.2.3 on 2025-07-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_rename_number_brazilianaddress_numero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brazilianaddress',
            old_name='complement',
            new_name='complemento',
        ),
        migrations.AlterField(
            model_name='brazilianaddress',
            name='numero',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
