# Generated by Django 5.2.3 on 2025-07-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_rename_complement_brazilianaddress_complemento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brazilianaddress',
            old_name='postal_code',
            new_name='cep',
        ),
        migrations.AlterField(
            model_name='brazilianaddress',
            name='complemento',
            field=models.CharField(blank='True', max_length=255, null=True, verbose_name='Complemento'),
        ),
    ]
