# Generated by Django 5.2.3 on 2025-07-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0015_rename_postal_code_brazilianaddress_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brazilianaddress',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
    ]
