# Generated by Django 5.2.3 on 2025-07-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_alter_brazilianaddress_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brazilianaddress',
            old_name='neighborhood',
            new_name='bairro',
        ),
    ]
