# Generated by Django 5.2.3 on 2025-07-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0017_rename_neighborhood_brazilianaddress_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brazilianaddress',
            name='country',
            field=models.CharField(max_length=2, verbose_name='País'),
        ),
    ]
