# Generated by Django 5.2.3 on 2025-07-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0018_alter_brazilianaddress_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrazilianAddress',
            new_name='BrazilianEndereco',
        ),
    ]
