# Generated by Django 5.2.3 on 2025-07-24 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0019_rename_brazilianaddress_brazilianendereco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrazilianEndereco',
            new_name='EnderecoBrasileiro',
        ),
    ]
