# Generated by Django 5.2.3 on 2025-07-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0020_rename_brazilianendereco_enderecobrasileiro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrazilianState',
            new_name='EstadoBrasileiro',
        ),
    ]
