# Generated by Django 5.2.3 on 2025-07-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0021_rename_brazilianstate_estadobrasileiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecobrasileiro',
            name='postal_system',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='usaddress',
            name='postal_system',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
