# Generated by Django 5.2.3 on 2025-07-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0022_enderecobrasileiro_postal_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usaddress',
            name='country',
        ),
    ]
