# Generated by Django 5.2.3 on 2025-07-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0023_remove_usaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='usaddress',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='enderecobrasileiro',
            name='country',
            field=models.CharField(default='BR', max_length=2, verbose_name='País'),
        ),
    ]
