# Generated by Django 5.2.3 on 2025-07-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0024_usaddress_country_alter_enderecobrasileiro_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_system', models.CharField(default='00000', max_length=5)),
                ('address', models.TextField(max_length=2000, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
