# Generated by Django 5.2.3 on 2025-08-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0025_genericaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericaddress',
            name='country',
            field=models.CharField(default='BR', max_length=2, verbose_name='País'),
        ),
    ]
