# Generated by Django 5.2.3 on 2025-08-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0026_genericaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericaddress',
            name='country',
            field=models.CharField(default='BR', max_length=2, verbose_name='Country'),
        ),
    ]
